version: "3.9"

services:
  tomcat:
    image: tomcat:10-jdk21
    container_name: tomcat-prod
    ports:
      - "${TOMCAT_PORT}:8080"
    volumes:
      - ./docker-servlet.war:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql-prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: